### ISSUE TITLE
Ubuntu 20.04 Qt6.2.2, Mouse pointer focus issue.

### ISSUE THREAD

**Issue by shujaatak** [wangwenx190/framelesshelper#101]
**mainwindow** and **widget** examples has mouse focus issue. None of the widgets receive mouse hover events after resizing the window. To bring mouse focus again, one have to click inside the window then the widgets start receiving mouse hover events again. I did not noticed this issue in **quick** example. 

To reproduce the issue, follow these steps:
Run either mainwindow or widget example.
Drag the application window border using Left Click + Mouse Dragging to resize the window.
Now try to hover mouse over Minimize, Maximize, Cross, or any other widget in the application.
I have noticed that sometime the hover do work but momentarily.

**Comment by wangwenx190** [comment]
It's a known issue on Linux platform, the workaround is also easy, you just need to send a mouse release event first before start dragging or resizing. But since I'm busy working on the 2.0 implementation, this issue may not be fixed until I released the first 2.0 snapshot.

**Comment by wangwenx190** [comment]
Sorry for the late reply

**Comment by wangwenx190** [comment]
2.0 is released, to be verified.

**Comment by shujaatak** [comment]
The issue is still there but it now appears randomly. I mean sometimes it disappears but sometimes it suddenly appears and then hover effect doesn't show up over the titlebar's minimize, maximize or cross buttons.

**Comment by wangwenx190** [comment]
OK, seems some workaround are not ported to 2.0, but don't worry, the fix is also not complicated and I'll fix them right away (before implementing 2.1 features).

**Comment by wangwenx190** [comment]
It should be fixed in the latest code, which I tagged with `2.0.1`. I've tested on Ubuntu 21.10, confirmed fixed. Please verify.

**Comment by shujaatak** [comment]
Not fixed. I just tested now and it's still there.
Surprisingly, I can reproduce this issue each time when I **move the window by dragging it using titlebar**.

**Comment by shujaatak** [comment]
QML example works just fine but other all three Qt-Widgets based examples has this issue.

**Comment by shujaatak** [comment]
The latest commit https://github.com/wangwenx190/framelesshelper/commit/3c0209c979d5b6453e5ad79e9c41f6af0224480a has no effect on this issue so I don't what issue it basically solves.

**Comment by wangwenx190** [comment]
Sorry to hear that. The fix is in general simple, we just need to send a mouse release event before we resize/move the window, commit 3c0209c is doing so, and I tested it on Ubuntu 21.10 and didn't find anything wrong, so I believed this issue is fixed. But maybe I missed something, let me re-check this.

**Comment by wangwenx190** [comment]
Finally I can reproduce this issue on my Ubuntu environment. It turns out that the solution is correct but I was using a wrong parameter which caused the mouse release event is not sent to the window manager properly. What a shame! Replacing the wrong parameter with the correct one fixes the issue.

**Comment by wangwenx190** [comment]
Hi, I've pushed new code and this time this issue should be fixed for real. The only change of the code is the correction of the wrong parameter.

**Comment by wangwenx190** [comment]
Previously I didn't noticed the mouse release event is not being sent properly because I'm using Qt's own move and resize functions and it seems on newer Qt versions they fixed the issue so even if the mouse release event is not being sent we can still have the expected behavior. But things became wrong when I switch to use my own implementation of startSystemMove/Resize ... Really sorry for the confusion that I caused, bro.
