### ISSUE TITLE
Some issues when transitioning between two monitors with different DPI

### ISSUE THREAD

**Issue by zxcv1884** [wangwenx190/framelesshelper#184]
Branch: main https://github.com/wangwenx190/framelesshelper/commit/648876b6b009937f39216a39b10610c50074b2f2
System: Windows 10.0.19045
Qt: 6.4.1 MSCV2019 64bit

I have three issues when moving between "1920x1080 scale:100%" and "2560x1400 scale:125%" monitors.
1. When the App is moved from 1080p to 2k monitor, the content not show up. (It can be solved when I disable QSGRendererInterface::Software)
2. When the App is stuck in the middle of the two monitors, it will keep switching.
3. When the App transitioning between two monitors, the window will expand.  #141

https://user-images.githubusercontent.com/39883679/203008557-da15d74b-182a-4c15-9367-f390040250b2.mp4

**Comment by zxcv1884** [comment]
The second issue is solved when comment out:
https://github.com/wangwenx190/framelesshelper/blob/648876b6b009937f39216a39b10610c50074b2f2/src/core/framelesshelper_win.cpp#L1130

**Comment by wangwenx190** [comment]
OK, that's good know, thanks! So the third issue (window will expand) still can't be solved by commenting the above four functions?

**Comment by zxcv1884** [comment]
Only the second(keep switching issue) is resolved.

**Comment by wangwenx190** [comment]
Issue 1 should not be a FramelessHelper bug, you can disable blur behind window and the issue should disappear.
Issue 2 can be fixed, but commenting out the function is not ideal, I'm trying to find a better solution.
Issue 3 can be workarounded, I'm working on a fix already.

**Comment by wangwenx190** [comment]
I'm still thinking about how to fix issue 2 perfectly, but can you check whether issue 3 is fixed by the latest commit or not? Thanks!

**Comment by zxcv1884** [comment]
I just tested [3961ecb](https://github.com/wangwenx190/framelesshelper/commit/3961ecb505aa885633851e4b378b897fb598e6c8), and issue 3 was not solved. 

Logs:
```
[2022/11/22 15:38:24.553] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x480E02 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/22 15:38:25.225] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x480E02 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/22 15:38:25.753] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x480E02 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/22 15:38:26.369] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x480E02 is Dpi(x: 96, y: 96, scale factor: 1)
```

**Comment by wangwenx190** [comment]
It's not 3961ecb, it's ebd3d6573f6dc606a849abf49c544073844baa62, is this a typo? Or are you testing the wrong commit?

**Comment by wangwenx190** [comment]
The new code reduces the window size after the DPI changes, it should not keep expanding like before. Do you notice any behavior change before and after ebd3d65?

**Comment by zxcv1884** [comment]
Sorry, wrong tag!
I mean ebd3d65 did not solve the issue 3.

According to my test:
- ebd3d65(newest)
When the App is moved from 1080p to 2k monitor, window height expand 30px
When the App is moved from 2k to 1080p monitor, window height expand 31px
- 3961ecb
When the App is moved from 1080p to 2k monitor, window height expand 38px
When the App is moved from 2k to 1080p monitor, window height expand 31px

**Comment by zxcv1884** [comment]
I saw you reduce the window size, but the reduced window is expanded again.

Logs:
```
[2022/11/22 16:37:33.901] <DEBUG> qml: window height:  566
[2022/11/22 16:37:33.901] <DEBUG> qml: window height:  566
[2022/11/22 16:37:33.901] <DEBUG> qml: window height:  566
[2022/11/22 16:37:33.903] <DEBUG> qml: window height:  566
[2022/11/22 16:37:36.405] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x730E72 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/22 16:37:36.485] <DEBUG> qml: window height:  567
[2022/11/22 16:37:36.492] <DEBUG> qml: window height:  567
[2022/11/22 16:37:36.519] <DEBUG> qml: window height:  536
[2022/11/22 16:37:36.536] <DEBUG> qml: window height:  567
[2022/11/22 16:37:38.315] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x730E72 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/22 16:37:38.386] <DEBUG> qml: window height:  598
[2022/11/22 16:37:38.386] <DEBUG> qml: window height:  598
[2022/11/22 16:37:38.419] <DEBUG> qml: window height:  567
[2022/11/22 16:37:38.436] <DEBUG> qml: window height:  598
```

**Comment by wangwenx190** [comment]
I'm working on another fix which should be more correct, but the Qt Quick demo doesn't work as expected, I'm trying to find out the reason ...

**Comment by wangwenx190** [comment]
OK, when I'm struggling to find the solution of the Qt Quick issue, I managed to find the root cause of issue 3. It's indeed a Qt bug, I haven't check which Qt version introduced this, but it's easy to fix. I'm working on a fix of it and hopefully Qt will merge my fix and all later Qt versions won't have this issue anymore.

**Comment by JulienMaille** [comment]
Congratulations for your hard work

**Comment by wangwenx190** [comment]
@zxcv1884 I just pushed new code. Can you test whether issue 3 is fixed or not? Thanks! And hopefully issue 2 will also be improved.
@JulienMaille  Thanks!

**Comment by wangwenx190** [comment]
The window will still expand?

**Comment by wangwenx190** [comment]
It really confuses me. Can you upload a new screen recording? Thanks!

**Comment by zxcv1884** [comment]
> It really confuses me. Can you upload a new screen recording? Thanks!


https://user-images.githubusercontent.com/39883679/203496382-e6dfb787-f67a-4baf-8369-28d2f65bb321.mp4

**Comment by wangwenx190** [comment]
OK, thanks, the window is apparently expanding indeed. But I don't quite understand what caused it now. The bug comes from the `WM_GETDPISCALEDSIZE` message. Qt wrongly ignores our custom margins so it sets a larger window size which contains an extra title bar height. However the recommended new window size in `WM_DPICHANGED` is readonly so we can't modify it. So I'm triggering a delayed event which will shrink the window size after Qt handles `WM_DPICHANGED`. And in my experiments this solution works well for both QtWidgets and QtQuick. Move window to different monitor should go through the same code path, so the solution should still be valid, that's why I'm rather confused at the moment.

**Comment by wangwenx190** [comment]
I'm trying the least ideal option, directly overriding the `WM_GETDPISCALEDSIZE` message. This can absolutely fix the issue but it completely ignores Qt's internal logic, so I say it's the least ideal choice.

**Comment by wangwenx190** [comment]
And here's the official fix for Qt: <https://codereview.qt-project.org/c/qt/qtbase/+/444760>

**Comment by zxcv1884** [comment]
Exactly, I tried to directly overriding the `WM_GETDPISVALEDSIZE` to solve issue 3, and it's works. :)

**Comment by wangwenx190** [comment]
> Exactly, I tried to directly overriding the `WM_GETDPISVALEDSIZE` to solve issue 3, and it's works. :)

How do you override the message? I still get a little expanded window after the DPI changes.

**Comment by zxcv1884** [comment]
I just put setWindowSize to `WM_GETDPISVALEDSIZE`. haha

```
    case WM_GETDPISCALEDSIZE: {
        const int titleBarHeight = Utils::getTitleBarHeight(windowId, false);
        const QSize expandedSize = data.params.getWindowSize();
        const QSize correctedSize = {expandedSize.width(), expandedSize.height() - titleBarHeight};
        data.params.setWindowSize(correctedSize);
    } break;
    case WM_DPICHANGED: {
        const Dpi dpi = {UINT(LOWORD(wParam)), UINT(HIWORD(wParam))};
        DEBUG.noquote() << "New DPI for window" << hwnd2str(hWnd) << "is" << dpi;
        // We need to wait until Qt has handled this message, otherwise everything
        // we have done here will always be overwritten.
        QTimer::singleShot(0, qApp, [data]() { // Copy the variables intentionally, otherwise they'll go out of scope when Qt finally use them.
            // Sync the internal window frame margins with the latest DPI, otherwise
            // we will get wrong window sizes after the DPI change.
            Utils::updateInternalWindowFrameMargins(data.params.getWindowHandle(), true);
        });
    } break;
```

**Comment by wangwenx190** [comment]
OK, thanks, it can be used as a temperory solution indeed, but it's still not perfect. I've uploaded new code, can you test it? Thanks!

**Comment by zxcv1884** [comment]
> OK, thanks, it can be used as a temperory solution indeed, but it's still not perfect. I've uploaded new code, can you test it? Thanks!

In most cases the window expand issue has been fixed, but with the minimumHeight set it will expand at the first time.

**Comment by wangwenx190** [comment]
> > OK, thanks, it can be used as a temperory solution indeed, but it's still not perfect. I've uploaded new code, can you test it? Thanks!
> 
> In most cases the window expand issue has been fixed, but with the minimumHeight set it will expand at the first time.

That's strange. Qt's own `WM_GETDPISCALEDSIZE` handler also don't handle anything about minimizeSize and maximizeSize

**Comment by wangwenx190** [comment]
From your log, the window height is not quite stable while you are moving it across monitors, will it return to 300 in the end or it continue to expanding little by little?

What will the log look like if you don't set the minimum height?

**Comment by zxcv1884** [comment]
> From your log, the window height is not quite stable while you are moving it across monitors, will it return to 300 in the end or it continue to expanding little by little?
> 
> What will the log look like if you don't set the minimum height?


It sometimes expand and sometimes reduce.
<details>
<summary>

```
Logs
```

</summary>

```
[2022/11/24 14:57:29.045] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:29.126] <DEBUG> qml: window height:  294
[2022/11/24 14:57:29.145] <DEBUG> qml: window height:  300
[2022/11/24 14:57:29.622] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:29.709] <DEBUG> qml: window height:  307
[2022/11/24 14:57:29.725] <DEBUG> qml: window height:  300
[2022/11/24 14:57:32.318] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:32.409] <DEBUG> qml: window height:  294
[2022/11/24 14:57:32.425] <DEBUG> qml: window height:  300
[2022/11/24 14:57:32.701] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:32.791] <DEBUG> qml: window height:  307
[2022/11/24 14:57:32.808] <DEBUG> qml: window height:  300
[2022/11/24 14:57:33.061] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:33.142] <DEBUG> qml: window height:  294
[2022/11/24 14:57:33.159] <DEBUG> qml: window height:  300
[2022/11/24 14:57:33.446] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:33.525] <DEBUG> qml: window height:  307
[2022/11/24 14:57:33.542] <DEBUG> qml: window height:  300
[2022/11/24 14:57:37.640] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:37.692] <DEBUG> qml: window height:  301
[2022/11/24 14:57:37.727] <DEBUG> qml: window height:  295
[2022/11/24 14:57:37.743] <DEBUG> qml: window height:  301
[2022/11/24 14:57:41.102] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:41.193] <DEBUG> qml: window height:  308
[2022/11/24 14:57:41.210] <DEBUG> qml: window height:  301
[2022/11/24 14:57:42.198] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:42.277] <DEBUG> qml: window height:  295
[2022/11/24 14:57:42.293] <DEBUG> qml: window height:  301
[2022/11/24 14:57:43.007] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:43.093] <DEBUG> qml: window height:  308
[2022/11/24 14:57:43.110] <DEBUG> qml: window height:  301
[2022/11/24 14:57:43.663] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:43.744] <DEBUG> qml: window height:  295
[2022/11/24 14:57:43.760] <DEBUG> qml: window height:  301
[2022/11/24 14:57:44.230] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:44.310] <DEBUG> qml: window height:  308
[2022/11/24 14:57:44.326] <DEBUG> qml: window height:  301
[2022/11/24 14:57:44.983] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:45.077] <DEBUG> qml: window height:  295
[2022/11/24 14:57:45.093] <DEBUG> qml: window height:  301
[2022/11/24 14:57:46.207] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:46.292] <DEBUG> qml: window height:  308
[2022/11/24 14:57:46.314] <DEBUG> qml: window height:  301
[2022/11/24 14:57:47.046] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:47.128] <DEBUG> qml: window height:  295
[2022/11/24 14:57:47.144] <DEBUG> qml: window height:  301
[2022/11/24 14:57:47.767] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:47.864] <DEBUG> qml: window height:  308
[2022/11/24 14:57:47.877] <DEBUG> qml: window height:  301
[2022/11/24 14:57:48.207] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:48.295] <DEBUG> qml: window height:  295
[2022/11/24 14:57:48.310] <DEBUG> qml: window height:  301
[2022/11/24 14:57:48.576] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:48.661] <DEBUG> qml: window height:  308
[2022/11/24 14:57:48.678] <DEBUG> qml: window height:  301
[2022/11/24 14:57:48.928] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:49.031] <DEBUG> qml: window height:  295
[2022/11/24 14:57:49.045] <DEBUG> qml: window height:  301
[2022/11/24 14:57:49.376] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:49.478] <DEBUG> qml: window height:  308
[2022/11/24 14:57:49.494] <DEBUG> qml: window height:  301
[2022/11/24 14:57:52.577] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:52.627] <DEBUG> qml: window height:  302
[2022/11/24 14:57:52.660] <DEBUG> qml: window height:  296
[2022/11/24 14:57:52.677] <DEBUG> qml: window height:  302
[2022/11/24 14:57:53.007] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:53.093] <DEBUG> qml: window height:  309
[2022/11/24 14:57:53.111] <DEBUG> qml: window height:  302
[2022/11/24 14:57:54.040] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:54.128] <DEBUG> qml: window height:  297
[2022/11/24 14:57:54.144] <DEBUG> qml: window height:  302
[2022/11/24 14:57:54.455] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:54.548] <DEBUG> qml: window height:  309
[2022/11/24 14:57:54.560] <DEBUG> qml: window height:  302
[2022/11/24 14:57:54.848] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:57:54.894] <DEBUG> qml: window height:  303
[2022/11/24 14:57:54.928] <DEBUG> qml: window height:  298
[2022/11/24 14:57:54.945] <DEBUG> qml: window height:  303
[2022/11/24 14:57:55.152] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:57:55.246] <DEBUG> qml: window height:  310
[2022/11/24 14:57:55.261] <DEBUG> qml: window height:  303
[2022/11/24 14:58:00.480] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:00.566] <DEBUG> qml: window height:  298
[2022/11/24 14:58:00.579] <DEBUG> qml: window height:  303
[2022/11/24 14:58:01.096] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:58:01.177] <DEBUG> qml: window height:  310
[2022/11/24 14:58:01.194] <DEBUG> qml: window height:  303
[2022/11/24 14:58:01.544] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:01.629] <DEBUG> qml: window height:  298
[2022/11/24 14:58:01.644] <DEBUG> qml: window height:  303
[2022/11/24 14:58:01.992] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:58:02.078] <DEBUG> qml: window height:  310
[2022/11/24 14:58:02.095] <DEBUG> qml: window height:  303
[2022/11/24 14:58:02.440] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:02.530] <DEBUG> qml: window height:  298
[2022/11/24 14:58:02.545] <DEBUG> qml: window height:  303
[2022/11/24 14:58:02.888] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:58:02.978] <DEBUG> qml: window height:  310
[2022/11/24 14:58:02.995] <DEBUG> qml: window height:  303
[2022/11/24 14:58:03.577] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:03.662] <DEBUG> qml: window height:  298
[2022/11/24 14:58:03.678] <DEBUG> qml: window height:  303
[2022/11/24 14:58:03.980] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:58:04.079] <DEBUG> qml: window height:  310
[2022/11/24 14:58:04.095] <DEBUG> qml: window height:  303
[2022/11/24 14:58:04.641] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:04.729] <DEBUG> qml: window height:  298
[2022/11/24 14:58:04.745] <DEBUG> qml: window height:  303
[2022/11/24 14:58:04.984] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:58:05.079] <DEBUG> qml: window height:  310
[2022/11/24 14:58:05.095] <DEBUG> qml: window height:  303
[2022/11/24 14:58:05.346] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:05.435] <DEBUG> qml: window height:  298
[2022/11/24 14:58:05.445] <DEBUG> qml: window height:  303
[2022/11/24 14:58:05.665] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:58:05.746] <DEBUG> qml: window height:  310
[2022/11/24 14:58:05.762] <DEBUG> qml: window height:  303
[2022/11/24 14:58:06.017] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:06.113] <DEBUG> qml: window height:  298
[2022/11/24 14:58:06.129] <DEBUG> qml: window height:  303
[2022/11/24 14:58:06.361] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:58:06.449] <DEBUG> qml: window height:  310
[2022/11/24 14:58:06.463] <DEBUG> qml: window height:  303
[2022/11/24 14:58:06.673] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:06.762] <DEBUG> qml: window height:  298
[2022/11/24 14:58:06.779] <DEBUG> qml: window height:  303
[2022/11/24 14:58:06.920] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 96, y: 96, scale factor: 1)
[2022/11/24 14:58:06.978] <DEBUG> qml: window height:  302
[2022/11/24 14:58:07.013] <DEBUG> qml: window height:  309
[2022/11/24 14:58:07.029] <DEBUG> qml: window height:  302
[2022/11/24 14:58:10.985] <DEBUG> wangwenx190.framelesshelper.core.impl.win: New DPI for window 0x2506C0 is Dpi(x: 120, y: 120, scale factor: 1.25)
[2022/11/24 14:58:11.062] <DEBUG> qml: window height:  297
[2022/11/24 14:58:11.079] <DEBUG> qml: window height:  302
```

</details>

**Comment by wangwenx190** [comment]
OK, thanks! It's normal. Qt's internal scale factor rounding algorithm is different with Windows's one, so it's expected that the window size doesn't perfectly match. It won't differ much proves we are not doing wrong.
