### ISSUE TITLE
missing cmake/utils.cmake

### ISSUE THREAD

**Issue by PerBothner** [wangwenx190/framelesshelper#202]
Running `cmake`, I get:
```
Make Error at CMakeLists.txt:54 (include):
  include could not find requested file:

    cmake/utils.cmake


CMake Error at CMakeLists.txt:60 (setup_project):
  Unknown CMake command "setup_project".
```
This is both Fedora Linux and macOS.

Did you forget to check in a file?

The relevant check-in appears to be:
```
commit 6063a962eb89040d23241224fcde51687d0f1d2d
Author: Yuhang Zhao <2546789017@qq.com>
Date:   Fri Jan 27 16:26:23 2023 +0800

    simplify cmake scripts
    
    Signed-off-by: Yuhang Zhao <2546789017@qq.com>
```

**Comment by wangwenx190** [comment]
You need to clone the submodules as well: `git clone --recursive https://github.com/wangwenx190/framelesshelper.git`

If you have cloned this repo already and want to clone the submodules separately, try run `git submodule update --init --recursive --remote`

**Comment by wangwenx190** [comment]
> The relevant check-in appears to be:

Yes, in that commit I moved the cmake scripts in this repo to a separate repo to make it usable for other projects, but I also add it back as a submodule.

**Comment by PerBothner** [comment]
Ooops.  Indeed, it builds now.

One more question before I close this: It's not obvious to me how to build and run the examples.  I tried `cd ../examples; cmake ..; make` whcih built a bunch of stuff but I can't find any executables.

**Comment by wangwenx190** [comment]
Just pass `-DFRAMELESSHELPER_BUILD_EXAMPLES=ON` when configure the top level project, and you'll get the executables in the cmake binary directory's `bin` dir.

**Comment by PerBothner** [comment]
Progress - I can build the examples.  But running bin/MainWindow on Fedora 37, running Gnome/X11 (not Wayland) causes:
```
Program received signal SIGSEGV, Segmentation fault.
```
A gdb stacktrace:
```
#0  QString::isEmpty() const (this=0x7ffff77ff268 <klibX11>)
    at /usr/include/qt5/QtCore/qstring.h:1078
#1  0x00007ffff778a8a4 in wangwenx190::FramelessHelper::SysApiLoader::isAvailable(QString const&, QString const&)
    (this=0x7ffff77fef80 <wangwenx190::FramelessHelper::(anonymous namespace)::Q_QGS_g_sysApiLoader::innerFunction()::holder>, library=..., function=...)
    at /home/bothner/Software/framelesshelper/src/core/sysapiloader.cpp:131
#2  0x00007ffff779ad5e in XInitThreads() ()
    at /home/bothner/Software/framelesshelper/src/core/platformsupport_linux.cpp:42
#3  0x00007ffff7fcccde in call_init
    (env=0x7fffffffd948, argv=0x7fffffffd938, argc=1, l=<optimized out>)
    at dl-init.c:70
#4  call_init
    (l=<optimized out>, argc=1, argv=0x7fffffffd938, env=0x7fffffffd948)
    at dl-init.c:26
#5  0x00007ffff7fccdcc in _dl_init
    (main_map=0x7ffff7ffe2c0, argc=1, argv=0x7fffffffd938, env=0x7fffffffd948)
    at dl-init.c:117
#6  0x00007ffff7fe38e0 in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in  ()
#8  0x00007fffffffdd2f in  ()
#9  0x0000000000000000 in  ()
```
On macOS (with HomeBrew) compilations fails:
```
[ 17%] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/micamaterial.cpp.o
/Users/bothner/Software/framelesshelper/src/core/utils_mac.mm:595:9: error: use of undeclared identifier 'registerUninitializeHook'
        registerUninitializeHook([](){
        ^
1 error generated.
```
```

**Comment by wangwenx190** [comment]
the macOS error is fixed by latest commit, just try updating your local repo

**Comment by wangwenx190** [comment]
OK, the segfault is reported by another user who is using Arch as well, looks like it's a general issue, let me fix it right away

**Comment by wangwenx190** [comment]
The segfault should be fixed now, please update your local repo and try, thanks!

**Comment by PerBothner** [comment]
I still get a segfault on Fedora. I'll take another look in the morning. (It's bedtime here in California.)

I did succeed in building and running the examples on macOS. It looks nice. I might use it for [DomTerm](https://domterm.org).

**Comment by wangwenx190** [comment]
OK. Have a good dream! I'll wait for your new findings!

**Comment by wangwenx190** [comment]
Another try to fix the segfault on linux has been uploaded. Please use the latest code for your next try.

**Comment by PerBothner** [comment]
It still segfaults.

My suspicion is it's an order-dependency issue: The `XInitThreads` function in `platformsupport_linux.cpp`  is called before the `klibX11` variable is constructed.

If I comment out the XInitThreads function, the examples start up.

**Comment by wangwenx190** [comment]
> It still segfaults.
> 
> My suspicion is it's an order-dependency issue: The `XInitThreads` function in `platformsupport_linux.cpp` is called before the `klibX11` variable is constructed.
> 
> If I comment out the XInitThreads function, the examples start up.

I already comment out `XInitThreads` in latest commit, did you forget to update your local repo?

**Comment by PerBothner** [comment]
> I already comment out XInitThreads in latest commit, did you forget to update your local repo?

No changes to  src/core/platformsupport_linux.cpp since 2023-01-24.

**Comment by wangwenx190** [comment]
> > I already comment out XInitThreads in latest commit, did you forget to update your local repo?
> 
> No changes to src/core/platformsupport_linux.cpp since 2023-01-24.

Yes, but if we don't call the function from outside, in theory everything inside that function won't be executed. Did you comment out the code in `platformsupport_linux.cpp` instead ?

**Comment by PerBothner** [comment]
The segfault happens with a clean fresh sources from GitHub, with a fresh build directory.

As you can see from [this stacktrace](https://github.com/wangwenx190/framelesshelper/issues/202#issuecomment-1418524972) the call to XInitThreads happens from dl-init.c, the dynamic library initialization code.  I don't know why, but based on [this](https://chromium.googlesource.com/native_client/nacl-newlib/+/65e6baefeb2874011001c2f843cf3083e771b62f/newlib/libc/sys/linux/dl/dl-init.c) it looks like XInitThreads gets marked with `DT_INIT`. I don't know enough about the dynamic linking machinery to know how that happens.

**Comment by wangwenx190** [comment]
OK, thanks! I have limited knowledge for the linux stuff, so maybe I should just comment out all the relevant code for now, until I really know what happened and how to solve.

**Comment by wangwenx190** [comment]
All relevant code have been commented out now.

**Comment by PerBothner** [comment]
It builds and runs fine now. Thanks.
