### ISSUE TITLE
[Windows] Window resize border location is inside of the application border

### ISSUE THREAD

**Issue by shujaatak** [wangwenx190/framelesshelper#3]
Fist thing first, illustration:
![screenshot2](https://user-images.githubusercontent.com/14161646/80299754-5cd9e880-87b0-11ea-9e84-4c21aac05a8f.png)

In the above illustration, the yellow color shows the area where mouse cursor changes to show that the user now can resize the window.
In framelesshelper application the mouse cursor changes when the mouse cursor is **inside** of the application window but in any other normal Windows application the cursor changes when the mouse is **on the application border or outside of the application border(in the window shadow area).** 
I think the resize border area is kept on border or outside of the border(in the window shadow area) to increase the client area so that the mouse could interact with the widgets inside of the application borders. So can this resize border be placed outside of the framelesshelper window border just like any other normal application window?

By the way, I noticed this when I got irritated by this unusual behavior as I missed clicking on the window border and mistakenly clicking on an other application running in the background.

Furthermore, I really like the way Mozilla does this(chrome way is not good, in my opinion). You can try to resize the Mozilla window by dragging the LEFT border and you won't see any flicker introduced in the minimize, maximize and close buttons but if you try the same with chrome then those buttons would flicker. While both Mozilla and Chrome provides custom window non-client area painting but retains the **resizing border location**.

I wish there was a stripped down **just window part** of the Mozilla browser so that the people like you ,me and others could benefit but that's another story. Mozilla is best in terms of GUI! But chrome is best in terms of other things.

**Comment by shujaatak** [comment]
I noticed that the Windows make that margins area(where mouse cursor changes to re-sizable one) as transparent around the window border, so I think in reality the outer region is part of the application but drawn transparent.
You ask from where I got this?
I was searching for making a [dwm/customframe](https://docs.microsoft.com/en-us/windows/win32/dwm/customframe) and I found [this repository](https://github.com/citorva/CustomWindow). I ran the "Composition Interface" example, keeping the default options and checked the fifth option from Theme group:
![screenshot3](https://user-images.githubusercontent.com/14161646/79808918-a24d7e80-8388-11ea-8036-d4f30942195b.png)

and I suddenly got amazing following results:

![screenshot2](https://user-images.githubusercontent.com/14161646/79808976-cc06a580-8388-11ea-8aac-bec63b83e7ed.png)

I have made a background picture which helps to see the transparent part of the window:

![screenshot1](https://user-images.githubusercontent.com/14161646/79809049-f8222680-8388-11ea-8068-f6664af9eb25.png)

I am not sure what I think is correct but what I see is a transparent window part outside of the application window borders.

**Comment by shujaatak** [comment]
Some links, projects and codes that may help to make [dwm/customframe](https://docs.microsoft.com/en-us/windows/win32/dwm/customframe).

**qdwmtest**
https://www.qtcentre.org/threads/55495-Non-client-area-painting-with-Qt
https://gist.github.com/d1manson/51aec9e2395478e775d8

**Qutty based on the above qdwmtest**
https://code.google.com/archive/p/qutty/

Qt implementation of custom DWM window:
https://github.com/citorva/CustomWindow

Custom WM_NCPAINT:
https://forum.qt.io/topic/3258/how-to-draw-to-the-windows-title-bar-with-qt-is-this-possible

https://forum.qt.io/topic/3258/how-to-draw-to-the-windows-title-bar-with-qt-is-this-possible/10

https://stackoverflow.com/questions/26826660/qt-wm-nccalcsize-black-showing

https://stackoverflow.com/questions/453069/qt-erase-background-windows-aero-glass

Changing the title bar color:
https://stackoverflow.com/questions/1487919/how-does-windows-change-aero-glass-color?rq=1

**Comment by shujaatak** [comment]
**Outstanding Delphi project**(I downloaded and run the source code and It 100% works!!!) **It has no borders issue too!**

Although it is written in Delphi but the native Windows APIs are same for both C++ and Delphi.

You can find the project articles here:
https://delphihaven.wordpress.com/2010/04/19/setting-up-a-custom-titlebar/
https://delphihaven.wordpress.com/2010/04/22/setting-up-a-custom-title-bar-reprise/
https://delphihaven.wordpress.com/2010/04/15/ever-felt-you-are-being-lied-too/

Project source code here(but it needs a free account):
http://cc.embarcadero.com/Item/27688

I have uploaded the source code to GitHub so that you may not have to go through any inconvenience:
https://github.com/shujaatak/Delphi_CustomFrame_DWM

I have tested the code with **Delphi-10** using **Embarcadero RAD Studio 2010 Delphi Architect**

As I haven't in-depth knowledge of making custom frameless window or helper so I am giving you pointers which may help you to improve the framelesshelper!

**Comment by wangwenx190** [comment]
>
> I wish there was a stripped down **just window part** of the Mozilla browser so that the people like you ,me and others could benefit but that's another story. Mozilla is best in terms of GUI! But chrome is best in terms of other things.
>
It's not another story, it's what I'm trying to do these days, what I'm trying to achieve using this repository, however things don't go well because Firefox's source code is very complicated and is not easy to abstract.
>
>I am not sure what I think is correct but what I see is a transparent window part outside of the application window borders.
>
You are correct. I learned this from a blog some days (maybe weeks) ago. The author of that blog is a professional Windows developer, so it's convincing to me. The resizable area is outside the window, except the top edge. I'm trying to simulate this behavior but I don't really know the solution. But thanks for your articles and repository, I believe it can be solved in the near future.

Thanks again, for your effort. You really helped me a lot.

**Comment by shujaatak** [comment]
See this one: https://github.com/Ochrazy/Qt-FramelessNativeWindow

It handles the border sizing and has support for mac, linux, and windows. You can get ideas from it for the Windows part.

**Comment by wangwenx190** [comment]
Thanks. I'll have a look at it.

**Comment by wangwenx190** [comment]
The resize area issue is now solved. I'm sorry that the solution isn't come from your articles but from Windows Terminal, which is a console application developed by Microsoft. But I really appreciate what you have done these days. I learned a lot from these articles and repositories.
I'll upload the code as soon as possible, but I'm quite busy these days so there may be some delay.
The new code looks perfect on Windows 10, but I'm wondering it's appearance on Windows 7. That's the only thing I'm worried about.

**Comment by shujaatak** [comment]
Congratulations! So happy that you found the solution! 
As far I think the problem lied in WM_NCCALCSIZE and  WM_ACTIVATE, but I am curious to see how you solved it. Waiting for your commit now!

**Comment by shujaatak** [comment]
Microsoft Terminal's minimize, maximize and close buttons flicker when the user resize the window using the LEFT resizing border, it's not like Mozilla Firefox, or Microsoft Edge. 
I hope you may have found a better solution.

**Comment by wangwenx190** [comment]
> 
> Microsoft Terminal's minimize, maximize and close buttons flicker when the user resize the window using the LEFT resizing border, it's not like Mozilla Firefox, or Microsoft Edge.
>
Yes, I can see the flicker, but it doesn't matter. The flicker is caused by other parts of the code. It won't affect the frameless window part. If you use `WinNativeEventFilter`, the three system buttons will be hidden and it's the user's responsibility to draw them. The trick to avoid the flicker is don't re-position and re-draw them when the window is resizing.

**Comment by shujaatak** [comment]
Now I am restless to see the framelesshelper in action!

**Comment by wangwenx190** [comment]
There's a small problem preventing the code from becoming perfect.
The new code needs to draw something in WM_PAINT, but if I use `*result = 0; return true;` in the message, the application will crash. If I just use `break;`, all the changes we made in that message will get lost (I guess it's covered by Qt's own painting). But if I move all the code to the widget's nativeEvent function, the application no longer crashes, however it results in a blank window if there exists `BeginPaint`. Now I'm struggling to find it's solution.
I use a hack I learned from Windows Terminal to bring the top frame border back because we get rid of it in WM_NCCALCSIZE. If you don't care about the lost of the top border, the WM_PAINT part will be no longer needed. However, a window without a top border doesn't look very good, so I want to bring it back if possible. Of course you can draw the border yourself through QPainter or anything you like, but this can't be done in NativeEventFilters.
Now I'm thinking of using SetWindowRgn or something like that to limit Qt's paint area to avoid our own painting be covered by Qt.

**Comment by wangwenx190** [comment]
I tested my code in OBS, despite of the top border issue, nothing flickers.

**Comment by wangwenx190** [comment]
The three invisible resize areas are in the window area, but they are outside the client area, and they will become visible because we turned the whole window area into client area in WM_NCCALCSIZE and I don't know how to make them be transparent again without breaking the frame shadow if the window frame is totally removed.
So I just keep the three sides of window frame, only get rid of the title bar and top border.
I need to do something in WM_PAINT to bring the top border back, but as I said before, some problems occurred.
According to the comments in Windows Terminal's source code, DWM will always draw the whole title bar if you modify the top edge of the client area in WM_NCCALCSIZE, unless you don't touch the top edge and let the whole title bar area get lost together with the top border. In other words, there is no way to only get rid of the title bar itself and keep the top border untouched. After many times of testing, I'm convinced it's true.

**Comment by shujaatak** [comment]
I just tested the updated **framwlesshelper** and it looks _almost_ perfect! By _almost_ I mean that the the three side borders appear as white lines if the window is focused else gray lines, the rest is **PERFECT!**  (The below screenshot shows the above behaviour).
I tested with both **QWidget** and **QMainWindow**, there is **_no flicker_** like in many other frameless helpers including Microsoft Terminal!
![screenshot2](https://user-images.githubusercontent.com/14161646/80197896-c2a36480-8638-11ea-8a13-1819478f979e.png)

**Comment by wangwenx190** [comment]
Thanks! I'm glad this repo can help you!
The window border's color should be the theme color or black when the window is active, it shouldn't be white. I'll have a look at it. But it's normal if it's color become gray when the window loses focus, it's not a bug.
As for the WM_PAINT problem, the Qt engineer tell me to try message hook. I'll give it a try.

**Comment by shujaatak** [comment]
When the window loses focus, the **left**, **bottom** and **right** borders becomes gray but the **top** remain same as when the window is in focus.

>As for the WM_PAINT problem, the Qt engineer tell me to try message hook. I'll give it a try.

I am hopeful that you will find the solution!

**Comment by wangwenx190** [comment]
After some discussion with the Qt engineer, I learned that developers shouldn't do anything in WM_PAINT because it will break Qt's backing store mechanism. However, the top border can't be seen if we don't do the hack in WM_PAINT. I managed to solve this yesterday, but the repository was completely re-written. I'll open a new branch for the new solution. The master branch will be reverted back to the original solution.

**Comment by wangwenx190** [comment]
The original solution supports Win7~Win10, but it has the resize area issue. The new solution only supports Windows 10 but it looks perfect. The only problem of the new solution is that it's more invasive (because of not using NativeEventFilter) so you will have to write more code if you want to integrate it into your own project.

**Comment by wangwenx190** [comment]
>
> the **top** remain same as when the window is in focus.
> 
That's because there is no top border actually. We have get rid of it in WM_NCCALCSIZE. So I need to use a hack to bring it back in WM_PAINT.

**Comment by shujaatak** [comment]
People have started transitioning towards Windows 10 after the Windows 7 End of Support. The Windows 10 market share is increasing very fast. 
![screenshot2](https://user-images.githubusercontent.com/14161646/80299968-23a27800-87b2-11ea-800a-b4d2316e3a32.png)
Ref: https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide

**Comment by shujaatak** [comment]
Yet another repository to get ideas from: https://github.com/oberth/custom-chrome

**Comment by shujaatak** [comment]
Would WM_NCPAINT help too?

**Comment by wangwenx190** [comment]
>
> People have started transitioning towards Windows 10 after the Windows 7 End of Support. The Windows 10 market share is increasing very fast.
> ![screenshot2](https://user-images.githubusercontent.com/14161646/80299968-23a27800-87b2-11ea-800a-b4d2316e3a32.png)
> Ref: https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide
>

Thanks! I have read it. It seems that Win10 has the most users in the world, however, things are quite different in my homeland, China. In China there are many people still use Win7 (some people even use XP! They don't care about safety or new features) in their office or at home, so it not a good idea to completely drop Win7 support, at least for Chinese. That's also the reason why I didn't delete the original solution. It's not perfect  but it works well from Win7 to Win 10 at least.

>
> Would WM_NCPAINT help too?
>

I tried it already but all the changes I made in WM_NCPAINT will get lost once Qt repaint the window. What's worse, it causes severe flickering when the window is being resized.

>
> Yet another repository to get ideas from: https://github.com/oberth/custom-chrome
>

Thanks! I'll have a look at it.!

**Comment by shujaatak** [comment]
>  I managed to solve this yesterday, but the repository was completely re-written. I'll open a new branch for the new solution. 

Can't wait to check it out!

**Comment by shujaatak** [comment]
**win10_only** branch behaves same as master branch i.e. the resizing borders are inside the application's window borders.

**Comment by wangwenx190** [comment]
>
> **win10_only** branch behaves same as master branch i.e. the resizing borders are inside the application's window borders.
>

You can try the new branch now. I pushed new code just now. Maybe the branch was created a bit earlier :)

The new code is not finished yet but is usable at least. There are some more detailed work to do but you can start testing it. I haven't look into the border color issue, but now the top border is back  at least.

I guess the border color issue is cause by DwmExtendFrameIntoClientArea. I'll check it when I'm free, but I'm quite busy these days, so it may take a while.

**Comment by wangwenx190** [comment]
The new solution uses [qtwinmigrate](https://github.com/qtproject/qt-solutions/tree/master/qtwinmigrate) from Qt Solutions, which is a commercial module in the Qt 4 times. It become open-source but unmaintained at some time.

The new solution uses a custom QWidget as a bridge, embed itself into a native Win32 window, so we can bring our top border back without breaking the backing store mechanism of Qt. However, this structure makes things much more complicated. There are much more work to do such as implementing basic window functions.

**Comment by shujaatak** [comment]
**win10_only** branch results with this stylesheet:

`widget->setStyleSheet("border: 1px solid red;background-color:green");`

(please click on the following screenshot to see it in it's original size)

![screenshot2](https://user-images.githubusercontent.com/14161646/80400664-8c821100-88d4-11ea-883e-2879f919b160.png)

What I was expecting? I was expecting a clean red border enclosing the window but as you can see the bottom side is missing the red border, also there is white border covering all four sides of the window.
No matter if I apply the stylesheet to widget or winWidget the results are same.

**Comment by wangwenx190** [comment]
Thanks for your testing!

I can see your snapshot. The white border around the four edges is the standard window frame border provided by Windows actually, so you can't paint anything on it. It's on the non-client area ,which is handled by DWM. Qt can only paint on client area. The color of it is controlled by system, you can change your theme color and the border color will also change.

But the border color should be black, not white, if you don't set a custom theme color. I'm still investigating it.

If you really want to draw your own frame border, I'm sorry that you will have to use the original solution because this can't be done in this solution. The original solution removed all the frame borders so you can draw anything you want on the window, including custom title bar and frame border. But this solution keeps the borders untouched, so their thickness and color are handled by DWM and thus can't be controlled by the developer. I don't know whether there are official Win32 APIs to modify them.

About the missing bottom border, I may know the reason, I'll try to fix it today.

**Comment by wangwenx190** [comment]
Commit 4aec1f147d9768dbdce49eb8cb08e5bb02aec0bc fixed the bottom border issue. The root cause is I miscalculated the content widget's size. Easy to fix. Border color issue still investigating.

**Comment by wangwenx190** [comment]
The reason why the frame border's color is white is now cleared. After calling DwmExtendFrameIntoClientArea, the frame borders become transparent (not white). It's a DWM bug and can be fixed in WM_PAINT. Still working on this.

**Comment by shujaatak** [comment]
>  But this solution keeps the borders untouched, so their thickness and color are handled by DWM and thus can't be controlled by the developer.

You are right, the stylesheet just draw inside the client area as it can be seen in the following fullscreen window(with the bottom border issue resolved):

![screenshot2](https://user-images.githubusercontent.com/14161646/80461157-49fd1a80-894e-11ea-8fc3-fde6701f3bab.png)

For me it seems that the border color is white not transparent, as you can see in the following screenshot:

![screenshot2](https://user-images.githubusercontent.com/14161646/80461538-dd365000-894e-11ea-9b89-8bb881d134fa.png)

If the border was transparent then in the above screenshot we could only see the red border.

**Comment by wangwenx190** [comment]
After some testing, I found that just calling DwmExtendFrameIntoClientArea won't change the border color, using it to extend the window frame will cause the border color issue. This can be reproduced in normal Win32 projects, so it's clear that the border color issue is not caused by the frameless code. I'll continue working on this.

> 
> For me it seems that the border color is white not transparent
> 

Yeah, you are right. I found this as well. If this is not the transparency bug mentioned in MSDN, it will be more difficult to solve.

> 
> ![screenshot2](https://user-images.githubusercontent.com/14161646/80299754-5cd9e880-87b0-11ea-9e84-4c21aac05a8f.png)
> 

Sorry for the late reply, but this picture is not accurate enough. For the original solution, the resize area is inside the window indeed, this is true, however, the window size is the exactly the same with the normal one, with addition of the three transparent resize areas. As what I mentioned before, we have turned the whole window area into the client area, including the invisible resize area. So the actual window size should be **the original client area + the non-client area (which includes the resize area)**

**Comment by shujaatak** [comment]
win10_only branch:
I think I found a hack/solution. First of all I noticed that Microsoft itself has no solution for the black top border. I noticed that all Windows Frameless Applications like Edge, Windows Settings, etc show a black top border when the application is active/in-focus otherwise show a semi-transparent border. So I thought why not we should do the same after all if Microsoft itself can't draw all borders of the same color then how can we. I noticed that Mozilla Firefox also has the same black top border(try to look closely).

Enough bragging, now here is what I did. I declared a bool variable `isActivated` before the `switch `statement inside `QWinNativeWindow::WndProc` and initialized it to `false`. Then I made the following changes:
```
    case WM_ACTIVATE:
    {
        if (wParam == NULL)
            isActivated = false;
        else
            isActivated = true;
    }
    case WM_DWMCOMPOSITIONCHANGED:
        UpdateFrameMarginsForWindow(hWnd, isActivated);
        break;
```
I added a `bool isActivated` parameter to `UpdateFrameMarginsForWindow` like this:
`VOID UpdateFrameMarginsForWindow(HWND handle, bool isActivated)`

And made only following changes inside `UpdateFrameMarginsForWindow` :
```
//margins.cyTopHeight = GetFrameSizeForWindow(handle, TRUE).top;
 if(!isActivated) margins.cyTopHeight = -1;
```
That's it! Now the window behaves same as Edge, Firefox etc.

![screenshot2](https://user-images.githubusercontent.com/14161646/80515416-5eb3cf80-899b-11ea-8c67-ea37b1ad503e.png)

**Comment by shujaatak** [comment]
As far as I think, now `win10_only `branch works perfectly but can I ask why this branch would not work  in windows-7 or what kind of problems it will show?

**Comment by shujaatak** [comment]
My bad, although Mozilla Firefox's top bar remains solid black with both Windows Light and Dark themes but Edge and other Windows applications top bar becomes semi-transparent with Light theme! My hack behaves same like Firefox, the top bar remains solid black no matter if I use Light or Dark theme.

**Comment by shujaatak** [comment]
On the other side Google Chrome shows only solid blue top border(I wonder how) no matter if I use Light or Dark Windows theme:

![screenshot2](https://user-images.githubusercontent.com/14161646/80519002-b86ac880-89a0-11ea-853f-35917e34d569.png)

**Comment by shujaatak** [comment]
Another observation, Edge sometimes show solid black top border and sometime show it as semi-transparent this means the Engineers behind it use some kind of hacks!

**Comment by shujaatak** [comment]
Related to `master `branch:
I noticed that as soon as I **maximize** or **minimize** the window by **double clicking on the title bar**, momentarily I can see through the window as if window becomes transparent. This problem doesn't occur in `win10_only `branch.

**Comment by wangwenx190** [comment]
Thanks for all your work! I really appreciate it!

The behavior of Google Chrome is not standard. The top border's color should not be blue unless the user change his/her theme color to blue. But from your snapshot I know it's not. So the conclusion is the top border is drawn by Chrome manually and it's color is wrong.

You can try notepad.exe or explorer.exe. In dark mode, it's four borders are all solid black when it has focus, they become gray when it loses focus. It means, in dark mode, all the window borders should be solid black, not only the top border. However, in light mode, all the four borders are gone (or become white? can't see clearly) when the window has focus, they become gray when it loses focus. It's very strange that UWP applications have a solid black border on top and I think this looks a bit strange.

I can judge whether the user is using light theme or dark theme through the registry, this is not difficult because I often do it. Maybe I can adjust the border color according to the user's settings.

Your solution works quite well, thanks for it! Maybe this issue can be solved within this week.

>
> As far as I think, now `win10_only `branch works perfectly but can I ask why this branch would not work in windows-7 or what kind of problems it will show?
>

`win10-only` branch just remove the top part of the window, it leaves the other three borders untouched. This doesn't look strange on Windows 10 because the border width on Windows 10 is just one pixel. However, the border width on Windows 7 is eight pixels (when DPI is 96), if we do the same thing just like what we do on Windows 10, the window will look terrible. I have tried it once, the window looks terrible indeed.

>
> Another observation, Edge sometimes show solid black top border and sometime show it as semi-transparent this means the Engineers behind it use some kind of hacks!
>

Maybe it's using `DwmGetColorizationColor` to get the theme color. This API has a bug according to the comments in Qt Win Extras's source code. It sometimes will return a wrong semi-transparent color. So Qt will read the color from the registry, not through this API, although it's the official way to do this. Or maybe I'm wrong and it's caused by the hacks. Chrome is full of hacks indeed. But who knows.

**Comment by shujaatak** [comment]
> You can try notepad.exe or explorer.exe. In dark mode, it's four borders are all solid black when it has focus, they become gray when it loses focus. It means, in dark mode, all the window borders should be solid black, not only the top border. 

What I see is Notepad.exe has **standard title bar** and I have noticed that, **in dark mode** and when it is focused, it shows all four borders as **dark-grayish color**(not solid black) **with transparency**, you have to look very closely for seeing through the borders. But when notepad is out of focus, it show all four borders as **light-grayish color with transparency**. While **in light mode** and when it is focused, notepad.exe shows all four borders as **white color with transparency** but when notepad is out of focus it shows all borders with the same **light-grayish color with transparency** like in dark mode.

![screenshot2](https://user-images.githubusercontent.com/14161646/80579958-420faa00-8a24-11ea-846f-b7526ab8a1de.png)


When in focus or out of focus, the Edge, Windows Settings Application etc. which have custom title bars show LEFT, BOTTOM and RIGHT borders **same** as Notepad.exe **in both Dark and Light modes**. In dark mode and when in focus, the top border is **solid black** and when out of focus it becomes **light-grayish color with transparency** like other three borders. While in light mode and when in focus, the top border is **dark-grayish with transparency** and when out of focus it becomes **light-grayish color with transparency** like other three borders.

![screenshot3](https://user-images.githubusercontent.com/14161646/80579978-46d45e00-8a24-11ea-85fc-715386121398.png)


In dark mode, I have noticed that the Edge top border is sometimes shown as **solid black** and sometimes **dark-grayish with transparency same as the other three borders**. I can see this behavior of the Edge top border by randomly clicking on title bar and sometimes on the widgets inside it like address bar etc.

**Comment by wangwenx190** [comment]
The little border is making everything more and more complicated.

>
> dark-grayish color(not solid black) with transparency
>

My English is not good, it's VERY hard for me to describe things like that. So maybe many of my words are lack of accuracy, I'm really sorry for that.

Here is the problem. We managed to bring the top border back by draw one manually, but it's color is not what we want. We can paint it using any color(brush) in WM_PAINT, but it can't be changed then. For example, once I draw a red line, I can't draw a blue line on top of it afterwards. However, we have to paint different colors for different states of the application, such as get focus, loses focus, user changed theme color, users switched to light or dark mode, etc.

No need to worry about the transparency problem. No matter what color you paint, the line will always become semi-transparent as long as it's painted on top of the border line.

**Comment by wangwenx190** [comment]
I'm also using 1909 so I don't know whether the behavior of the four window borders vary between different Windows versions or not.

**Comment by wangwenx190** [comment]
And thanks for your snapshots. They make things much more clear.

**Comment by shujaatak** [comment]
What I noticed today is that Google Chrome uses accent color as the top border color.

![screenshot2](https://user-images.githubusercontent.com/14161646/80754661-d83cf080-8b48-11ea-981d-8917d063860a.png)

**Comment by wangwenx190** [comment]
I tried `QWizard` just now. It also looks frameless on Windows 10 (it has a title bar on Win7), and it looks quite well. But it's four window borders are also white when it has focus. That's what this code initially does. What about just use this (I mean, forget about the borders, just leave it white, since it doesn't look bad) ?

>
> Apparently Edge and Visual Studio use a dirty trick(a transparent window in the background)
>

Actually, this is what many software does. It will look perfect if you embed your window into a larger transparent window and draw a frame shadow yourself. But it's very dirty indeed. I don't like this kind of tricks. I'll never do it.

**Comment by shujaatak** [comment]
The white borders would look OK with a light theme but they would look horrible with a dark theme of an application.

**Comment by shujaatak** [comment]
By the way, highly successful commercial projects like Adobe products like Photoshop etc., AnyDesk, BlueStacks, Camtasia, and many more softwares which I have used but now can't remember the names have the resizing borders inside the application borders just like framelesshelper! 
I think your approach used in master branch is quite well and would work for most of the projects and hopefully users won't be annoyed as most of the users have already got used to it.

**Comment by wangwenx190** [comment]
>
> By the way, highly successful commercial projects like Adobe products like Photoshop etc., AnyDesk, BlueStacks, Camtasia, and many more softwares which I have used but now can't remember the names have the resizing borders inside the application borders just like framelesshelper!
>

Yes, I've noticed this as well. But I think the border issue can be solved. I'm still investigating it.

**Comment by shujaatak** [comment]
> Yes, I've noticed this as well. But I think the border issue can be solved. I'm still investigating it.

Only those achieve who have the highest determination and I believe in you!

**Comment by wangwenx190** [comment]
> 
> Only those achieve who have the highest determination and I believe in you!
>

Thanks for your trust! I really appreciate it!

However, you'd better use the master branch, because it seems that the border issue can't be solved in the near future.

**Comment by wangwenx190** [comment]
Have you tried the latest version of Firefox? Currently it's 76.0.1

I found that it's minimize, maximize and close buttons flicker when the user resize the window using the left resizing border. If I recall correctly, they don't flicker in older versions, do they?

**Comment by shujaatak** [comment]
For me minimize, maximize and close buttons do not flicker. They remain where they are. I also have the same version of Firefox 76.0.1 .

**Comment by shujaatak** [comment]
I have found an another another repository which uses Frameless Window. It has all minimize, maximize animations etc. The only problem I can see is that you can see the flicker when you resize the window. 
https://github.com/Zettlr/Zettlr

**Comment by wangwenx190** [comment]
> For me minimize, maximize and close buttons do not flicker. They remain where they are. I also have the same version of Firefox 76.0.1 .

![111](https://user-images.githubusercontent.com/17877450/82309482-c6d35f80-99f5-11ea-8505-f90e1928feb7.gif)

Firefox flickers on my machine. Don't know why.

> I have found an another another repository which uses Frameless Window. It has all minimize, maximize animations etc. The only problem I can see is that you can see the flicker when you resize the window.
> https://github.com/Zettlr/Zettlr

Thanks. But after some quick search, I found that it doesn't use C++ and it doesn't use any Win32 API. Maybe the frameless part is not in this repo.

**Comment by wangwenx190** [comment]
My PC broke down last week and it can't be repaired so I have to buy a new one. The same version firefox do not flicker in my new computer. Strange.

**Comment by shujaatak** [comment]
Yes it's indeed strange!

**Comment by wangwenx190** [comment]
Sorry for the delay, but do you have time to test the latest code of the master branch? I believe it's much better than before.

**Comment by shujaatak** [comment]
I will surely try to test the latest code of the master branch in the coming days. I hope it would be much polished and smooth as I believe in your work and dedication!

**Comment by SelastinGeorge** [comment]
i have a solution for solving the flickering. you may have a look at it.
Try using this code in NCCALCSIZE

This one is C# code just convert it to C++,for your project. it helped me a lot.

```
case WM_NCCALCSIZE:
 if( wParam != IntPtr.Zero ) {
       handled = true;
       var client = (RECT)Marshal.PtrToStructure( lParam, typeof( RECT ) );
       client.Bottom -= 1;
       Marshal.StructureToPtr( client, lParam, false );
       }
break;
```

Once u apply this code your window resize will look like this:

[Flickerless Sample](https://github.com/Selastin-George/UWP-Host/raw/master/Sample/Assets/demo/flicker.gif)

You may have a look at my project too.
[UWPHost](https://github.com/Selastin-George/UWP-Host)

In my project i gave this patch to my Microsoft.Windows.Shell dll.

**Comment by SelastinGeorge** [comment]
this is having a smaller effect in the latest windows 10. It causes a tiny amount of flickering if u resize continuously. The new Windows  updates caused some bug in this project. The blue border turns white and so on.

**Comment by wangwenx190** [comment]
> 
> Once u apply this code your window resize will look like this:
> 
> [Flickerless Sample](https://github.com/Selastin-George/UWP-Host/raw/master/Sample/Assets/demo/flicker.gif)
> 
What did you do to preserve the window frame (the four blue borders)?

**Comment by wangwenx190** [comment]
> 
> 
> i have a solution for solving the flickering. you may have a look at it.
> Try using this code in NCCALCSIZE, Responding to WM_NCCALCSIZE with any RECT smaller than the window solves the problem.
> 
> This one is C# code just convert it to C++,for your project. it helped me a lot.
> 
> ```
> case WM_NCCALCSIZE:
>  if( wParam != IntPtr.Zero ) {
>        handled = true;
>        var client = (RECT)Marshal.PtrToStructure( lParam, typeof( RECT ) );
>        client.Bottom -= 1;
>        Marshal.StructureToPtr( client, lParam, false );
>        }
> break;
> ```
> 
> Once u apply this code your window resize will look like this:
> 
> [Flickerless Sample](https://github.com/Selastin-George/UWP-Host/raw/master/Sample/Assets/demo/flicker.gif)
> 
> You may have a look at my project too.
> [UWPHost](https://github.com/Selastin-George/UWP-Host)
> 
> In my project i gave this patch to my Microsoft.Windows.Shell dll.

Thanks! It works for me as well!

**Comment by SelastinGeorge** [comment]
> > Once u apply this code your window resize will look like this:
> > [Flickerless Sample](https://github.com/Selastin-George/UWP-Host/raw/master/Sample/Assets/demo/flicker.gif)
> 
> What did you do to preserve the window frame (the four blue borders)?

The blue borders where working in the previous versions of windows currently it shows white borders. but i was able to remove the full border from window without affecting the resize and animations. 
Actually this RECT controls the margin from the Client Area and Non-Client Area so if the margin is set to a small value we will be able to get the border of original window.
just change the client RECT values to this:

```
client.Bottom -= 0;
client.Left -= 1;
client.Right -= 0;
client.Top -= 0;
```

it removes the border and then u can draw a custom border manually. if you are using wpf just set `BorderThickness="1"` and `BorderBrush="<your border color>"`.
But custom border drawing might cause a little bit of flickering so i think its better to use Directx for drawing the border around window.

**Comment by SelastinGeorge** [comment]
i'm currently working to bring the acrylic blur effect to a custom win32 or WPF window. I was able to develop the blur effect on any given input, but i don't know how to get the visual behind the window and use it as the input for my blurring code. do you have any idea to make this? i'm not an expert at this. I tried using setWindowComposition and DWM blur behind. but it causes lagging and flickering.

if you have any idea please let me know.

**Comment by wangwenx190** [comment]
> 
> 
> > > Once u apply this code your window resize will look like this:
> > > [Flickerless Sample](https://github.com/Selastin-George/UWP-Host/raw/master/Sample/Assets/demo/flicker.gif)
> > 
> > 
> > What did you do to preserve the window frame (the four blue borders)?
> 
> The blue borders where working in the previous versions of windows currently it shows white borders. but i was able to remove the full border from window without affecting the resize and animations.
> Actually this RECT controls the margin from the Client Area and Non-Client Area so if the margin is set to a small value we will be able to get the border of original window.
> just change the client RECT values to this:
> 
> ```
> client.Bottom -= 0;
> client.Left -= 1;
> client.Right -= 0;
> client.Top -= 0;
> ```
> 
> it removes the border and then u can draw a custom border manually. if you are using wpf just set `BorderThickness="1"` and `BorderBrush="<your border color>"`.
> But custom border drawing might cause a little bit of flickering so i think its better to use Directx for drawing the border around window.
>

In one word, the four borders are painted by yourself, manually? I thought you are using the standard borders provided by the system.

**Comment by wangwenx190** [comment]
> 
> 
> i'm currently working to bring the acrylic blur effect to a custom win32 or WPF window. I was able to develop the blur effect on any given input, but i don't know how to get the visual behind the window and use it as the input for my blurring code. do you have any idea to make this? i'm not an expert at this. I tried using setWindowComposition and DWM blur behind. but it causes lagging and flickering.
> 
> if you have any idea please let me know.
>

First of all, you have to know the Acrylic effect was introduced in Win10, it's not supported on Win7, Win8 and Win8.1. Of course, you can also make a window become semi-transparent (or blur or whatever) through DWM APIs, but that's not the *Arcylic effect*.

For WPF windows, there is a blog post on it that goes into great detail: <https://blog.walterlv.com/post/set-window-composition-attribute.html>, but it's written in Chinese. See also: <https://blog.walterlv.com/post/win10/2017/10/02/wpf-transparent-blur-in-windows-10.html> and <https://blog.walterlv.com/post/create-blur-background-window.html>.

For Win32 windows, the trick is to use the undocumented API `SetWindowCompositionAttribute`. That's the only API you need to call to enable the Acrylic effect for a normal win32 window, no need to call any DWM functions. There are many articles and blog posts teching people how to use this API.

**Comment by wangwenx190** [comment]
> 
> For Win32 windows, the trick is to use the undocumented API SetWindowCompositionAttribute. That's the only API you need to call to enable the Acrylic effect for a normal win32 window, no need to call any DWM functions. There are many articles and blog posts teching people how to use this API.
>
For a C++ version, you can see how I use it:
https://github.com/wangwenx190/framelesshelper/blob/09100a18455a633ae4ab9daf8127e0ff51e5b245/winnativeeventfilter.cpp#L2258

**Comment by SelastinGeorge** [comment]
I have used this articles before .There is still a problem in windows 10 Build 1903 and > the acrylic effect lags. Which means if i drag the window the window will move slowly only. and thats the problem i was not able to fix. Microsoft haven't given a fix till now. so i'm trying to recreate the acrylic effect.

There are 2 ways to do that one is the method mentioned over here:
1.[Win32 Composition Samples - Acrylic Blur](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/AcrylicEffect) (This one still lags)
2. Using Magnifier. (Its a bit bad idea)

The only way i see to get the visual behind window is using the magnifier api. and listen to the callback `MagGetImageScalingCallback`, This will return the image behind the window. Then i can use this image by  applying saturation,exclusion blend and gaussian blur effect using directX gives me Acrylic blur effect.

But the problem arises here is when the `MagGetImageScalingCallback` is set and if i move the window almost near to the right side the Program Crashes with an exception like memory access violation.

Checkout the issue here:[Windows Magnifier Window Cause exception when setting MagSetImageScalingCallback](https://stackoverflow.com/questions/64318817/windows-magnifier-window-cause-exception-when-setting-magsetimagescalingcallback)

and this is the issue which has been hunting me for last week. if u know a way to fix it please let me know.

**Comment by wangwenx190** [comment]
>
> if i drag the window the window will move slowly only
>
Yes, I've encountered with this problem as well.
>
> thats the problem i was not able to fix
>
Me too.
>
> Microsoft haven't given a fix till now.
>
That's a bad news.
>
> if u know a way to fix it please let me know.
>
Sorry, it's far beyond my limit. I'm not an expert at such things.

**Comment by JulienMaille** [comment]
Seems like this guys achieve acrylic with Qt?
https://forum.qt.io/topic/92168/qtitannavigation-1-4-has-been-released

**Comment by wangwenx190** [comment]
> Seems like this guys achieve acrylic with Qt?
> https://forum.qt.io/topic/92168/qtitannavigation-1-4-has-been-released

Looks fantastic but unfortunately doesn't open source.

**Comment by JulienMaille** [comment]
I installed their demo version. The toolbar/borders look very authentic. However the acrylic mode is fake and doesn't look like the screenshot I posted. It's probably an homemade blur.

**Comment by SelastinGeorge** [comment]
i'm trying my level best to recreate the acrylic blur. no all i want is to get the visual behind  the window. if i was having the source code for Magnifier api i would have finished it.

**Comment by wangwenx190** [comment]
> 
> 
> I installed their demo version. The toolbar/borders look very authentic. However the acrylic mode is fake and doesn't look like the screenshot I posted. It's probably an homemade blur.

@JulienMaille I have tried their demo applications just now. The appearance looks quite impressive indeed.

Summary of the good points:
1. The window doesn't flicker when resizing.
2. The resize area is outside the window, just like a native win32 window.
3. The window still has its four borders and their color can respond to the system theme color change in time.
4. The context menu can be brought up by right-click in the title bar area.

I don't have two monitors so I can't test whether #21 will happen or not.

It has some small bugs, but to me it's perfect enough.

As for the acrylic effect, it looks OK for me. Whether it's a real acrylic effect or homemade one doesn't matter too much to me.

**Comment by wangwenx190** [comment]
@JulienMaille I want to buy its source code but sadly I really can't afford some price like $699😂

**Comment by wangwenx190** [comment]
Actually, there are some open source repositories achieve this, such as Microsoft's [Terminal](https://github.com/microsoft/terminal), but it's really hard to integrate their code into Qt.

**Comment by JulienMaille** [comment]
> i'm trying my level best to recreate the acrylic blur. no all i want is to get the visual behind the window. if i was having the source code for Magnifier api i would have finished it.

https://forum.qt.io/post/570259
this is XAML specific and to achieve the same with C++ and Qt you'd have to dig deep into [DirectComposition ](https://docs.microsoft.com/en-us/windows/win32/directcomp/directcomposition-portal)API which essentially gives you direct access to the window's DirectX framebuffer where you can apply the blur effect efficiently.

**Comment by JulienMaille** [comment]
> I don't have two monitors so I can't test whether #21 will happen or not.
no bugs when changing screens

> It has some small bugs, but to me it's perfect enough.
which ones?

> As for the acrylic effect, it looks OK for me. Whether it's a real acrylic effect or homemade one doesn't matter too much to me.
Nah it's bad :p

**Comment by wangwenx190** [comment]
>
>> It has some small bugs, but to me it's perfect enough.
>
> which ones?
>
The context menu can't be brought up from keyboard and the three system buttons sometimes fail to work. And I sometimes fail to use keyboard shortcut to maximize or restore the window.

**Comment by SelastinGeorge** [comment]
> > i'm trying my level best to recreate the acrylic blur. no all i want is to get the visual behind the window. if i was having the source code for Magnifier api i would have finished it.
> 
> https://forum.qt.io/post/570259
> this is XAML specific and to achieve the same with C++ and Qt you'd have to dig deep into [DirectComposition ](https://docs.microsoft.com/en-us/windows/win32/directcomp/directcomposition-portal)API which essentially gives you direct access to the window's DirectX framebuffer where you can apply the blur effect efficiently.
> 
> and maybe this too? https://stackoverflow.com/a/44010660

ya i have built the blurring code using Direct Composition api, but there is no way that i can access the visual behind the window. i have already tried that NO_REDIRECTIONBITMAP stuff. it just makes the window transparent that's it.

All the windows, including your desktop, taskbar are drawn by a compositor if we need to get the visual behind the window we must capture the area for window before it is drawn by the compositor. and in that way Microsoft created an api for accessing the visual before the window is drawn and that is used by uwp apps.

So i think it's difficult to access the visual behind window.

**Comment by JulienMaille** [comment]
Anything here that could help? https://github.com/Mr1008/Falcon/blob/9403379382edb53b4e4b1a03a730cfebf651dba3/Falcon.UI/DirectXWindow.cpp

**Comment by SelastinGeorge** [comment]
Nope it doesn't work

**Comment by wangwenx190** [comment]
> 
> 
> The toolbar/borders look very authentic.
>
It looks a lot like the system window frame but I'm afraid it's still a self painted one. Still under invesgating.

>
> However the acrylic mode is fake and doesn't look like the screenshot I posted. It's probably an homemade blur.
>
I'm sure it's an homemade blur now because the real Acrylic effect for Win32 windows is quite broken and can't be fixed from the application develops' side.

**Comment by SelastinGeorge** [comment]
Can you pls send the link of the exe file of the demo

**Comment by wangwenx190** [comment]
> 
> 
> Can you pls send the link of the exe file of the demo

<https://www.devmachines.com/qtitannavigation-overview.html>

You can download their SDK. The binaries are included in the SDK. You can use it freely within 30 days.

It's designed for Qt, maybe you need to install Qt first.

**Comment by SelastinGeorge** [comment]
Let me check

**Comment by SelastinGeorge** [comment]
can you please tell me how to move resize borders outside a window. i'm using c# wpf with dwm extended client area

> The resize area issue is now solved. I'm sorry that the solution isn't come from your articles but from Windows Terminal, which is a console application developed by Microsoft. But I really appreciate what you have done these days. I learned a lot from these articles and repositories.
> I'll upload the code as soon as possible, but I'm quite busy these days so there may be some delay.
> The new code looks perfect on Windows 10, but I'm wondering it's appearance on Windows 7. That's the only thing I'm worried about.

can you plz share the code for that part.

**Comment by SelastinGeorge** [comment]
we can create acrylic effect using SetWindowDisplayAffinity() method but later i noticed that there is a big disadvantage we cannot take the screenshot or video of that window. it won't appear in screenshots or video.

so another dead end for acrylic effect.

**Comment by wangwenx190** [comment]
>
> can you please tell me how to move resize borders outside a window
>
If you don't modify the client rect in `WM_NCCALCSIZE`, the whole window frame will be lost, the resize area is gone at the same time, so you'll need to do some extra work in `WM_NCHITTEST` to simulate the resize area, and that's what most software do. If you are doing this, the resize area will be inside of the window. If you want to preserve the resize area (aka move the resize area outside of the window), you need to make sure there is enough space for the resize area. That's how I do it:
https://github.com/wangwenx190/framelesshelper/blob/c3d54c616d5ec451b5f694f8f4808748d12966bc/winnativeeventfilter.cpp#L1490

If you are looking for a C# version, see how WPF do it: <https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs>
>
> can you plz share the code for that part.
>
You can see how I handle the `WM_NCCALCSIZE` message:
https://github.com/wangwenx190/framelesshelper/blob/0debbb890fdbe070ab959da7fd3d058db1fe4d6f/winnativeeventfilter.cpp#L1378

**Comment by SelastinGeorge** [comment]
do you have any c# code for this. my code looks like this:<br>

```
 const int resizeFrameWidth = 11;
        const int captionHeight = 33;

        public enum HT { CLIENT = 1, CAPTION = 2, LEFT = 10, RIGHT, TOP, TOPLEFT, TOPRIGHT, BOTTOM, BOTTOMLEFT, BOTTOMRIGHT }

        [StructLayout( LayoutKind.Sequential )]
        public struct Margins { public int left, right, top, bottom; }

        [DllImport( "user32.dll" )]
        public static extern bool SetWindowPos( IntPtr hWnd, IntPtr hWndInsertAfter, int x, int y, int cx, int cy, int flags );

        [DllImport( "dwmapi.dll" )]
        public static extern bool DwmDefWindowProc( IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, out IntPtr result );

        [DllImport( "dwmapi.dll", PreserveSig = false )]
        public static extern void DwmExtendFrameIntoClientArea( IntPtr hwnd, ref Margins pMarInset );

        protected override void OnSourceInitialized( EventArgs e ) {
            base.OnSourceInitialized( e );

            var hWndSource = HwndSource.FromHwnd( new WindowInteropHelper( this ).Handle );
            hWndSource.CompositionTarget.BackgroundColor = Colors.Transparent;

            var nonClientArea = new Margins{ 
                left = resizeFrameWidth, top = captionHeight, bottom = resizeFrameWidth, right = resizeFrameWidth
            };
            DwmExtendFrameIntoClientArea( hWndSource.Handle, ref nonClientArea );

            hWndSource.AddHook( WndProc );

            // FRAMECHANGED | NOMOVE | NOSIZE
            SetWindowPos( hWndSource.Handle, new IntPtr( ), 0, 0, 0, 0, 0x0020 | 0x0002 | 0x0001 );
        }

        private IntPtr WndProc( IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled ) {

            switch( msg ) {
                case 0x0083: // NCCALCSIZE
                    if( wParam != IntPtr.Zero ) handled = true;
                    break;
                case 0x0084: // NCHITTEST
                    handled = true;

                    IntPtr dwmHitTest;
                    if( DwmDefWindowProc( hwnd, msg, wParam, lParam, out dwmHitTest ) ) {
                        return dwmHitTest;
                    }

                    var mousePosition = PointFromScreen( new Point( lParam.ToInt32( ) & 0xFFFF, lParam.ToInt32( ) >> 16 ) );

                    var isTop = mousePosition.Y <= resizeFrameWidth;
                    var isBottom = mousePosition.Y >= ActualHeight - resizeFrameWidth;
                    var isLeft = mousePosition.X <= resizeFrameWidth;
                    var isRight = mousePosition.X >= ActualWidth - resizeFrameWidth;

                    var hitTest = HT.CLIENT;
                    if( isTop ) {
                        if( isLeft ) hitTest = HT.TOPLEFT;
                        else if( isRight ) hitTest = HT.TOPRIGHT;
                        else hitTest = HT.TOP;
                    }
                    else if( isBottom ) {
                        if( isLeft ) hitTest = HT.BOTTOMLEFT;
                        else if( isRight ) hitTest = HT.BOTTOMRIGHT;
                        else hitTest = HT.BOTTOM;
                    }
                    else if( isLeft ) hitTest = HT.LEFT; 
                    else if( isRight ) hitTest = HT.RIGHT; 
                    else if( mousePosition.Y <= captionHeight ) hitTest = HT.CAPTION;

                    return new IntPtr( (int)hitTest );
            }
            return IntPtr.Zero;
        }
```

**Comment by SelastinGeorge** [comment]
> do you have any c# code for this. my code looks like this:
> 
> ```
>  const int resizeFrameWidth = 11;
>         const int captionHeight = 33;
> 
>         public enum HT { CLIENT = 1, CAPTION = 2, LEFT = 10, RIGHT, TOP, TOPLEFT, TOPRIGHT, BOTTOM, BOTTOMLEFT, BOTTOMRIGHT }
> 
>         [StructLayout( LayoutKind.Sequential )]
>         public struct Margins { public int left, right, top, bottom; }
> 
>         [DllImport( "user32.dll" )]
>         public static extern bool SetWindowPos( IntPtr hWnd, IntPtr hWndInsertAfter, int x, int y, int cx, int cy, int flags );
> 
>         [DllImport( "dwmapi.dll" )]
>         public static extern bool DwmDefWindowProc( IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, out IntPtr result );
> 
>         [DllImport( "dwmapi.dll", PreserveSig = false )]
>         public static extern void DwmExtendFrameIntoClientArea( IntPtr hwnd, ref Margins pMarInset );
> 
>         protected override void OnSourceInitialized( EventArgs e ) {
>             base.OnSourceInitialized( e );
> 
>             var hWndSource = HwndSource.FromHwnd( new WindowInteropHelper( this ).Handle );
>             hWndSource.CompositionTarget.BackgroundColor = Colors.Transparent;
> 
>             var nonClientArea = new Margins{ 
>                 left = resizeFrameWidth, top = captionHeight, bottom = resizeFrameWidth, right = resizeFrameWidth
>             };
>             DwmExtendFrameIntoClientArea( hWndSource.Handle, ref nonClientArea );
> 
>             hWndSource.AddHook( WndProc );
> 
>             // FRAMECHANGED | NOMOVE | NOSIZE
>             SetWindowPos( hWndSource.Handle, new IntPtr( ), 0, 0, 0, 0, 0x0020 | 0x0002 | 0x0001 );
>         }
> 
>         private IntPtr WndProc( IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled ) {
> 
>             switch( msg ) {
>                 case 0x0083: // NCCALCSIZE
>                     if( wParam != IntPtr.Zero ) handled = true;
>                     break;
>                 case 0x0084: // NCHITTEST
>                     handled = true;
> 
>                     IntPtr dwmHitTest;
>                     if( DwmDefWindowProc( hwnd, msg, wParam, lParam, out dwmHitTest ) ) {
>                         return dwmHitTest;
>                     }
> 
>                     var mousePosition = PointFromScreen( new Point( lParam.ToInt32( ) & 0xFFFF, lParam.ToInt32( ) >> 16 ) );
> 
>                     var isTop = mousePosition.Y <= resizeFrameWidth;
>                     var isBottom = mousePosition.Y >= ActualHeight - resizeFrameWidth;
>                     var isLeft = mousePosition.X <= resizeFrameWidth;
>                     var isRight = mousePosition.X >= ActualWidth - resizeFrameWidth;
> 
>                     var hitTest = HT.CLIENT;
>                     if( isTop ) {
>                         if( isLeft ) hitTest = HT.TOPLEFT;
>                         else if( isRight ) hitTest = HT.TOPRIGHT;
>                         else hitTest = HT.TOP;
>                     }
>                     else if( isBottom ) {
>                         if( isLeft ) hitTest = HT.BOTTOMLEFT;
>                         else if( isRight ) hitTest = HT.BOTTOMRIGHT;
>                         else hitTest = HT.BOTTOM;
>                     }
>                     else if( isLeft ) hitTest = HT.LEFT; 
>                     else if( isRight ) hitTest = HT.RIGHT; 
>                     else if( mousePosition.Y <= captionHeight ) hitTest = HT.CAPTION;
> 
>                     return new IntPtr( (int)hitTest );
>             }
>             return IntPtr.Zero;
>         }
> ```

i'm not good at c++

**Comment by wangwenx190** [comment]
>
> i'm using c# wpf with dwm extended client area
>
The resize area will not be affected by `DwmExtendFrameIntoClientArea()`.

And if you want to preserve the resize area, you'll have to deal with the top frame issue. Once you preserved the resize area, the top frame will get lost at the same time. You can hack into the `WM_PAINT` message to bring it back. I don't know how to do this in WPF.

**Comment by SelastinGeorge** [comment]
the resize area is affected

**Comment by SelastinGeorge** [comment]
the resize handle appears inside the window not outside

**Comment by wangwenx190** [comment]
>
> but later i noticed that there is a big disadvantage
>
Can we solve the issue first and then consider the disadvantage?
>
>  it won't appear in screenshots or video.
>
Why?

**Comment by SelastinGeorge** [comment]
> > but later i noticed that there is a big disadvantage
> 
> Can we solve the issue first and then consider the disadvantage?
> 
> > it won't appear in screenshots or video.
> 
> Why?

because SetWindowDisplayAffinity() is actually used to hide windows from screenshots or capturing

**Comment by wangwenx190** [comment]
If you are using WPF, why do this by yourself? Microsoft has offered the `WindowChrome` feature to make a frameless window in WPF.

**Comment by SelastinGeorge** [comment]
ya i have used it but will it fix the resize border issue

**Comment by wangwenx190** [comment]
>
> ya i have used it but will it fix the resize border issue
>
I don't use WPF and UWP so I don't know the answer to your question, but since it's provided by Microsoft, I think it's more reliable than open-source projects.

**Comment by SelastinGeorge** [comment]
it doesn't fix the issue still same problem.
![image](https://user-images.githubusercontent.com/72641365/97027210-06d7d900-1578-11eb-8570-80c02ba13726.png)

**Comment by SelastinGeorge** [comment]
sorry the cursor is not captured

**Comment by wangwenx190** [comment]
>
> case 0x0083: // NCCALCSIZE
                    if( wParam != IntPtr.Zero ) handled = true;
                    break;
>
As what I said before, the whole window frame will get lost if you are doing this. For WM_NCCALCSIZE, the lParam stores the client rect, you need to modify it to give enough space for the resize area:
https://github.com/dotnet/wpf/blob/5102a35819e0d703d3dc7074d2ad473e6ee7390b/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs#L598

**Comment by wangwenx190** [comment]
when DPI is 96, the resize area is 8px width/height.

> 
> 
> sorry the cursor is not captured

Can you update the picture? I want to see it.

**Comment by SelastinGeorge** [comment]
thank you it worked,pretty well

**Comment by wangwenx190** [comment]
>
> it worked,pretty well
>
Is your new code worked or the window chrome feature worked?

**Comment by SelastinGeorge** [comment]
the window chrome feature worked i added extra 8 pixels

**Comment by wangwenx190** [comment]
>
> i added extra 8 pixels
>
Don't hard code this value. You can acquire it from the system. You should adjust it together with the DPI.

**Comment by SelastinGeorge** [comment]
ya i can do it with SystemParameters from chrome window right

**Comment by wangwenx190** [comment]
So you are using the Window Chrome feature instead of your own code?

**Comment by SelastinGeorge** [comment]
both mixed one. i am creating custom window based on DWMExtentClientArea and also using window chrome as a reference

**Comment by wangwenx190** [comment]
Can the frameless window show the theme color correctly?

**Comment by SelastinGeorge** [comment]
i'm going to rebuild my previous project from scratch and trying to make it perfect. Here is the old one :[UWPHost](https://github.com/Selastin-George/UWP-Host)

**Comment by SelastinGeorge** [comment]
> Can the frameless window show the theme color correctly? I mean, the borders.

no i should draw it separately

**Comment by wangwenx190** [comment]
If the resize area is outside of the window, you don't need to draw it manually.

**Comment by SelastinGeorge** [comment]
no currently the window only comes with a white border

**Comment by SelastinGeorge** [comment]
and i think it is a piece of the window behind


> it doesn't fix the issue still same problem.
> ![image](https://user-images.githubusercontent.com/72641365/97027210-06d7d900-1578-11eb-8570-80c02ba13726.png)

have a look at this

**Comment by wangwenx190** [comment]
The white border is the non-client area. What we do in the WM_NCCALCSIZE block is to cover the non-client area with the client area. That's why the title bar is gone.

**Comment by SelastinGeorge** [comment]
But when we apply DWMExtentClientArea  the border of window disappears

**Comment by wangwenx190** [comment]
Yes you are right and I think it's a bug. I think the border have no reason to disappear. You can bring the border back by passing {0,0,0,0} to DwmExtendFrameIntoClientArea.

**Comment by SelastinGeorge** [comment]
let me check

**Comment by SelastinGeorge** [comment]
if i give all zeros to DwmExtendFrameIntoClientArea the window border will not appear and the window shadow is also gone

**Comment by wangwenx190** [comment]
If any of the margin is non-zero, the border will certainly disappear, and that behavior is not documented anywhere, that's why I think it's a bug.

**Comment by SelastinGeorge** [comment]
But one advantage is that the window never flickers. in the latest windows 10 even though the fix  for flicker is applied. some times it causes a slight flicker. but when i used zero for margin its flickerless

**Comment by wangwenx190** [comment]
Microsoft only say this API can extend the frame into the client area, but it didn't say the border will disappear.

**Comment by SelastinGeorge** [comment]
ya it looks like Microsoft is not going to solve the problem

**Comment by wangwenx190** [comment]
> 
> 
> But one advantage is that the window never flickers. in the latest windows 10 even though the fix for flicker is applied. some times it causes a slight flicker. but when i used zero for margin its flickerless

Yes you are right. I noticed this as well. But I don't know the reason. It's like magic to me.

**Comment by wangwenx190** [comment]
> 
> 
> ya it looks like Microsoft is not going to solve the problem

You can check the File Explorer, its border also disappears.

**Comment by SelastinGeorge** [comment]
ya the new build 1903 has more bugs than features.

**Comment by wangwenx190** [comment]
> Wow this issue has quite a lot of comments. What is the final status on this? Resize area is still inside the window with framelesshepler, which makes it difficult to resize if the widgets inside the window already interact with the mouse. Is there anything we can do to make resizing easier (in previous case you have to be exactly on the border)

Currently we removed the whole window frame so the resize area is inside the window now. I know this will make resizing difficult in some situations, but I tested several commercial applications and found that most of them is the same with this repo, they also resize inside the window. The way they workaround the issue is to make enough space for the widgets, don't put widgets too near to the window border.

If you want to resize outside of the window, you'll have to preserve the window frame, and this is only doable on Win10 because the window will look super ugly if you preserve the window frame on Win7. Currently it's not possible to do this for Qt applications because the window will lack the top frame and look rather weired (but if you don't care you can continue), I'm working on a patch to make this work on Qt, but I'm not sure whether Qt engineers will accept it or not.

**Comment by wangwenx190** [comment]
This issue will be fixed in the next major release - 2.0

**Comment by wangwenx190** [comment]
Fixed in 2.0

**Comment by shujaatak** [comment]
It's not fixed yet! I tested it in Ubuntu 20.04 and the resize region is still inside the window! 
Please reopen this issue.

Once I find time then I will test it on windows too.

**Comment by wangwenx190** [comment]
@shujaatak No need to test on Windows, I mainly develop on Windows and I'm sure this issue is fixed on Windows. This issue was closed because this issue mainly focus on the Windows platform. For Linux I'll create a separate issue to track this.
